# Generated by Django 6.1.1 on 2026-09-25 13:42

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('doador', models.CharField(max_length=255)),
                ('tipo_entrada', models.CharField(default='Doação Recebida', max_length=100)),
                ('item', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=100)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recibo_emitido', models.BooleanField(default=False)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstoqueItem',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=100)),
                ('unidade', models.CharField(default='kg', max_length=20)),
                ('qtd_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qtd_entradas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qtd_saidas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('validade', models.DateField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=20)),
                ('tipo_label', models.CharField(max_length=100)),
                ('item_nome', models.CharField(max_length=255)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unidade', models.CharField(max_length=20)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_novo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('origem_destino', models.CharField(max_length=255)),
                ('responsavel', models.CharField(max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='sgi.estoqueitem')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('status_acolhimento', models.CharField(default='Acolhido', max_length=50)),
                ('leito', models.CharField(blank=True, max_length=50, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observacoes_clinicas', models.TextField(help_text='Anotações do acolhimento/reabilitação.')),
                ('data_entrada', models.DateField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prontuarios', to='sgi.paciente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentoAnexo',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(choices=[('laudo', 'Laudo Médico'), ('termo', 'Termo de Acolhimento'), ('identidade', 'Documento de Identidade'), ('receita', 'Receita Médica'), ('foto', 'Foto Cadastral'), ('outro', 'Outro Anexo')], default='outro', max_length=50)),
                ('arquivo', models.FileField(upload_to='documentos/%Y/%m/')),
                ('tamanho_bytes', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='sgi.paciente')),
                ('prontuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='sgi.prontuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProntuarioChunk',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('texto_chunk', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='sgi.prontuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
