# Generated by Django 6.1.1 on 2026-09-25 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoanexo',
            name='erro_processamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentoanexo',
            name='hash_sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='documentoanexo',
            name='processado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentoanexo',
            name='status_processamento_ia',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro')], db_index=True, default='PENDENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='documentoanexo',
            name='texto_extraido',
            field=models.TextField(blank=True, help_text='Texto extraído via OCR / parser de PDF para indexação RAG', null=True),
        ),
        migrations.AddField(
            model_name='prontuariochunk',
            name='documento_anexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chunks_vetoriais', to='sgi.documentoanexo'),
        ),
    ]
