# Generated by Django 6.1.1 on 2026-09-25 17:24

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0002_documentoanexo_erro_processamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuariochunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
