# Generated by Django 6.1.1 on 2026-09-25 17:30

import pgvector.django.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0003_prontuariochunk_embedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='prontuariochunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embed_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
