"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega as variáveis do .env se existir
load_dotenv(os.path.join(BASE_DIR, '.env'))


def get_secret(name: str, default: str = None) -> str:
    """
    Recupera segredos corporativos de forma segura para Docker Swarm (ADR 011).
    Ordem de precedência:
    1. Arquivo montado em /run/secrets/{name} (Docker Secrets em RAM tmpfs)
    2. Variável de ambiente (os.environ) com o nome exato do secret
    3. Variável de ambiente sem prefixo 'scsi_' em caixa alta (ex: POSTGRES_PASSWORD)
    4. Valor default fornecido
    """
    secret_path = Path('/run/secrets') / name
    if secret_path.is_file():
        try:
            return secret_path.read_text(encoding='utf-8').strip()
        except Exception:
            pass
    val = os.environ.get(name)
    if val is not None:
        return val
    clean_name = name.removeprefix('scsi_').upper()
    val = os.environ.get(clean_name)
    if val is not None:
        return val
    return default


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_secret('scsi_django_secret_key', os.environ.get('SECRET_KEY', 'django-insecure-+t#g6j6rs_ewi8(_jlvl=+4*6^h@@t^fl3a#3sh7#+)g3f9yzr'))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    # Third-party apps
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'channels',
    'django_celery_results',
    # Local apps
    'sgi',
]

MIDDLEWARE = [
    'sgi.middleware.CloudflareClientIPMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

if 'test' in sys.argv or os.environ.get('DJANGO_USE_SQLITE_TEST', 'false').lower() == 'true':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }
    class DisableMigrations:
        def __contains__(self, item):
            return True
        def __getitem__(self, item):
            return None
    MIGRATION_MODULES = DisableMigrations()
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': get_secret('scsi_postgres_db', os.environ.get('POSTGRES_DB', 'dr_jesus_db')),
            'USER': get_secret('scsi_postgres_user', os.environ.get('POSTGRES_USER', 'drjesus_admin')),
            'PASSWORD': get_secret('scsi_postgres_password', os.environ.get('POSTGRES_PASSWORD', 'drjesus_senha_forte_123')),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
            'CONN_MAX_AGE': 600,  # Reutilização persistente de conexões (mitiga overhead TCP/DNS)
        }
    }




# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# --- SCSI: Storage Soberano de Arquivos (Substituindo o Supabase Storage) ---
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB teto total do payload
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440           # 2.5MB no heap RAM (DevOps: evita OOM em uploads simultâneos)


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# --- SCSI: Autenticação Soberana (Substituindo o Supabase Auth) ---

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# --- SCSI: Defesas e CORS para Swarm / React (Fase 7) ---

CORS_ALLOW_CREDENTIALS = True
# Lendo os domínios permitidos do .env (fallback para o dev do Vite)
CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:5173').split(',')
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost:5173').split(',')

# Permite que o Django reconheça quando estiver atrás do HTTPS do Traefik e da Cloudflare
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True


# --- SCSI: Redis / Channels / Celery com Docker Secrets (Fase 7.1) ---
REDIS_HOST = os.environ.get('REDIS_HOST', 'localhost')
REDIS_PORT = os.environ.get('REDIS_PORT', '6379')
REDIS_PASSWORD = get_secret('scsi_redis_password', os.environ.get('REDIS_PASSWORD', ''))
REDIS_AUTH = f":{REDIS_PASSWORD}@" if REDIS_PASSWORD else ""

# Channels WebSockets
ASGI_APPLICATION = 'core.asgi.application'
REDIS_URL = os.environ.get('REDIS_URL', f"redis://{REDIS_AUTH}{REDIS_HOST}:{REDIS_PORT}/1")
USE_REDIS_CHANNEL = os.environ.get('USE_REDIS_CHANNEL', 'false').lower() == 'true'

if USE_REDIS_CHANNEL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_URL],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer'
        }
    }

# Celery & RabbitMQ Broker
RABBITMQ_HOST = os.environ.get('RABBITMQ_HOST', 'localhost')
RABBITMQ_PORT = os.environ.get('RABBITMQ_PORT', '5672')
RABBITMQ_USER = get_secret('scsi_rabbitmq_user', os.environ.get('RABBITMQ_USER', 'guest'))
RABBITMQ_PASS = get_secret('scsi_rabbitmq_password', os.environ.get('RABBITMQ_PASSWORD', 'guest'))

DEFAULT_CELERY_BROKER = f"amqp://{RABBITMQ_USER}:{RABBITMQ_PASS}@{RABBITMQ_HOST}:{RABBITMQ_PORT}//"
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', DEFAULT_CELERY_BROKER)
CELERY_BROKER_HEARTBEAT = 30
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Arquiteto Fix: Redis como Result Backend volátil (evita bloat no PostgreSQL) com TTL de 1h
DEFAULT_CELERY_RESULT = f"redis://{REDIS_AUTH}{REDIS_HOST}:{REDIS_PORT}/2"
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', DEFAULT_CELERY_RESULT)
CELERY_RESULT_EXPIRES = 3600  # 1 hora para expurgo automático de metadados temporários

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutos máximo para pipelines RAG de IA

# Backend & DevOps Fixes: Distribuição justa e resiliência contra crash/OOM
CELERY_WORKER_PREFETCH_MULTIPLIER = 1      # Impede que um worker monopolize jobs pesados de IA
CELERY_TASK_ACKS_LATE = True               # Confirma mensagem apenas após execução bem-sucedida
CELERY_TASK_REJECT_ON_WORKER_LOST = True   # Re-enfileira automaticamente se o worker sofrer crash/OOM

# Isolamento estrito de Filas (ADR Celery Worker):
# - default: tarefas operacionais rápidas
# - ia_tasks: tarefas pesadas cognitivas (LangGraph, OCR, Ollama embeddings)
CELERY_TASK_DEFAULT_QUEUE = 'default'
CELERY_TASK_ROUTES = {
    'sgi.tasks_ia.*': {'queue': 'ia_tasks'},
    'sgi.tasks.*': {'queue': 'default'},
}

# --- SCSI: Otimizações de Testes Unitários e End-to-End ---
if 'test' in sys.argv:
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True
    CELERY_BROKER_URL = 'memory://'
    CELERY_RESULT_BACKEND = 'cache+memory://'




